### ISSUE TITLE
Замечания по Лабораторной работе №1 "replace"

### ISSUE THREAD

**Issue by AniSkyWorker** [Relz/OOP#1]
- [x] следует загружать файлы необходимые для инициализации проекта (vcxproj) в репозиторий, иначе возникает много неудобств при запуске ваших лаб
- [x] test.bat написан неправильно: ошибка при получении аргумента переданного из командной строки. 
- [x] в функцию IsFileExists ifstream нужно передавать по константной ссылке, так как мы не меняем его содержимое
- [x] вместо проверок типа if (search.size() == 0) можно вызвать метод search.empty(), который вернет результат в виде bool
- [x] почему бы не использовать вместо isLineProcessing проверку внутри конструкции while, а вместо minPos, уже имеющийся pos, проанализируйте и примените:

``` C++
void Replace(ifstream &inputFile, ofstream &outputFile, string const& search, string const& replace)
{
    string line;
    size_t pos = 0;
    while (getline(inputFile, line))
    {
        pos = 0;
        while (pos = line.find(search, pos),pos != string::npos )
        {
                line.replace(pos, search.size(), replace);
                pos += replace.size();
        }
        outputFile << line << "\n";
    }
}
```
- [x] расширьте тесты для проверки некорректного числа переданных аргументов и несуществующих файлов

**Comment by AniSkyWorker** [comment]
k = 0.7

**Comment by Relz** [comment]
@AniSkyWorker ,
Спасибо за замечания, исправился =)

**Comment by AniSkyWorker** [comment]
на будущее вместо - "\n" можно писать std::endl, а такие вещи, как 5(необходимое число аргументов) выносить в константы
k = 1

**Comment by alexey-malov** [comment]
можно закрыть, баллы выставлены
